#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# Regenerate the CAN packing/unpacking code from adas.dbc.
#
# adas.dbc is the source of truth for the vehicle bus. Nothing in contracts/gen
# is hand-edited: change the DBC, re-run this, commit both.
#
#   ./contracts/generate.sh          regenerate
#   ./contracts/generate.sh --check  fail if the output is stale (for CI)
#
# Requires cantools. If it is not on PATH the script builds a throwaway venv:
#   python -m pip install cantools
# ---------------------------------------------------------------------------
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DBC="$HERE/adas.dbc"
OUT="$HERE/gen"
DB_NAME="adas"

CHECK=0
[[ "${1:-}" == "--check" ]] && CHECK=1

# --- locate cantools ------------------------------------------------------
if command -v cantools >/dev/null 2>&1; then
    CANTOOLS=(cantools)
elif python -c "import cantools" >/dev/null 2>&1; then
    CANTOOLS=(python -m cantools)
elif python3 -c "import cantools" >/dev/null 2>&1; then
    CANTOOLS=(python3 -m cantools)
else
    echo "error: cantools not found. Install it with:" >&2
    echo "    python -m pip install cantools" >&2
    exit 1
fi

# --- validate before generating -------------------------------------------
# A DBC that only parses leniently will produce code that silently disagrees
# with the file, so insist on strict.
"${CANTOOLS[@]}" dump "$DBC" >/dev/null

# cantools stamps the generation date into every file, which would make the
# output differ on every run - a permanent spurious git diff, and a --check
# that can never pass. Drop the date, keep the version.
strip_timestamp() {
    sed -i -E 's/(generated by cantools version [0-9]+\.[0-9]+\.[0-9]+).*$/\1./' "$@"
}

generate_into() {
    "${CANTOOLS[@]}" generate_c_source --output-directory "$1" \
        --database-name "$DB_NAME" "$DBC" >/dev/null
    strip_timestamp "$1/$DB_NAME.c" "$1/$DB_NAME.h"
}

if (( CHECK )); then
    TMP="$(mktemp -d)"
    trap 'rm -rf "$TMP"' EXIT
    generate_into "$TMP"
    STALE=0
    for f in "$DB_NAME.c" "$DB_NAME.h"; do
        if ! diff -u "$OUT/$f" "$TMP/$f"; then
            STALE=1
        fi
    done
    if (( STALE )); then
        echo "error: contracts/gen is stale - run contracts/generate.sh" >&2
        exit 1
    fi
    echo "contracts/gen is up to date."
    exit 0
fi

mkdir -p "$OUT"
generate_into "$OUT"

echo "Generated:"
ls -1 "$OUT"
